name: Build and Push Docker Image

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu) # 就是通过这一步进行释放空间
        uses: jlumbroso/free-disk-space@main
        with:
          # 这个可能会删除一些你实际需要的工具，所以建议还是 false 让它保留
          # 如果你打算尝试移除它，可以再腾出大约6GB的空间
          tool-cache: false

          # 如果有你需要使用的，将其设置为 false ，比如这里我们要构建Docker，Docker相关的工具是不能删的
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # # 使用tmate进行调试
      # - name: Setup tmate session
      #   uses: mxschmitt/action-tmate@v3
      #   timeout-minutes: 30

      # # 提前终止
      # - name: Error step
      #   run: |
      #     exit 1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Build Docker image
        run: |
          docker build -t mineru-sglang:latest -f Dockerfile .

      - name: Login to Aliyun Container Registry
        uses: docker/login-action@v2
        with:
          registry: registry.cn-hangzhou.aliyuncs.com
          username: ${{ secrets.ALIYUN_DOCKER_USERNAME }}
          password: ${{ secrets.ALIYUN_DOCKER_PASSWORD }}

      - name: Push Docker image to Aliyun Container Registry
        run: |
          docker tag mineru-sglang:latest registry.cn-hangzhou.aliyuncs.com/mineru-sglang:latest
          docker push registry.cn-hangzhou.aliyuncs.com/mineru-sglang:latest
