name: Build and Compress Docker Image

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    steps:      
      - name: Start frp tunnel
        uses: cirunlabs/frp-tunnel-action@v1.2.0
        with:
          timeout_minutes: 1
          frp_server: '{{ secrets.FRP_SERVER }}'
          frp_token: '${{ secrets.FRP_TOKEN }}'
          local_port: 22
          remote_port: 6000

      # 故意报错，提前终止
      - name: Error step
        run: |
          echo "This step is intentionally failing to demonstrate error handling."
          exit 1

      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install docker
          sudo apt-get update
          sudo apt-get install -y p7zip-full

      - name: Build Docker image
        run: |
          # 先拉取基础镜像以便进行层去重
          docker pull vllm/vllm-openai:v0.7.3
          docker build -t vllm:v0.9.1 .

      - name: Export and compress image
        run: |
          sudo mkdir -p /mnt/tmp
          sudo chmod 777 /mnt/tmp
          # 软链接替代/var/lib/docker/tmp，防止硬盘空间不足
          sudo mkdir -p /mnt/docker/tmp
          sudo ln -s /mnt/docker/tmp /var/lib/docker/tmp
          # 使用diffdocker导出去重后的tar
          python diffdocker.py --tempdir /mnt/tmp save vllm/vllm-openai:v0.7.3 vllm:v0.9.1 -o image.tar

          # 使用7z压缩
          7z a -t7z -mx9 image.7z image.tar

          # 使用gzip压缩
          gzip -9 < image.tar > image.tar.gz

          # 删除原始tar文件
          rm image.tar

          # 获取文件大小并比较
          sz1=$(stat -c%s image.7z)
          sz2=$(stat -c%s image.tar.gz)
          mkdir -p compressed-image

          echo "Size of 7z: $sz1 bytes"
          echo "Size of gz: $sz2 bytes"

          if [ $sz1 -le $sz2 ]; then
            echo "7z compression is smaller"
            rm image.tar.gz
            mv image.7z compressed-image
          else
            echo "gz compression is smaller"
            rm image.7z
            mv image.tar.gz compressed-image
          fi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: compressed-image
          retention-days: 1
